server:
  port: 8081
spring:
  application:
    name: auth-service
  main:
    allow-bean-definition-overriding: true  
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/auth_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    database: postgresql      
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    