server:
  port: 8762
spring:
  application:
    name: spring-cloud-gateway
  main:
    web-application-type: reactive
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      filter:
        add-request-header:
          enabled: true
      routes:
#        - id: indentity-1
#          uri: http://localhost:8082
#          predicates:
#            - Path=/api/identity/**
#          filters:
#            - StripPrefix=1
#            - TokenRelay=
#            - KeycloakOauth2Filter
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/**
          filters:
            - AuthenticationFilter
        - id: service-1
          uri: http://localhost:8080
          predicates:
            - Path=/api/service1/**
          filters:
            - AuthenticationFilter