server:
  port: 8082
  servlet:
    context-path: /api/identity
spring:
  application:
    name: indentity-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/test-realm
            